global:
  scrape_interval: 1m
  evaluation_interval: 1m
  scrape_timeout: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: logging
    static_configs:
      - targets: ["localhost:3030"]
