global:
  scrape_interval: 1s
  evaluation_interval: 2s
  scrape_timeout: 0s900ms
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: logging
    static_configs:
      - targets: ["go-exporter:3030"]
