version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    pull_policy: if_not_present
    network_mode: host
    restart: unless-stopped
    container_name: jahad_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/data
#    ports:
#      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    pull_policy: if_not_present
    network_mode: host
    restart: unless-stopped
    container_name: jahad_grafana
#    ports:
#      - "3000:3000"

volumes:
  prometheus-data: